name: Sync Cards to Firebase

on:
  workflow_dispatch:
  push:
    paths:
      - 'cards/*.json'
      - '.github/workflows/deploy-cards-to-realtime-db.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🚀 Upload all JSON files to Realtime Database
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "Uploading all cards/*.json files to Firebase..."
          for file in cards/*.json; do
            key=$(basename "$file" .json)
            echo "→ Uploading $file to /cards/$key"
            firebase database:set /cards/$key "$file" \
              --project nft-cards-1cd82 \
              --token "$FIREBASE_TOKEN"
          done

      - name: 🧹 Delete removed cards from Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "Checking for removed card keys..."
          firebase database:get /cards \
            --project nft-cards-1cd82 \
            --token "$FIREBASE_TOKEN" > allCards.json

          for key in $(jq -r 'keys[]' allCards.json); do
            if [ ! -f "cards/$key.json" ]; then
              echo "→ Removing /cards/$key (not found in GitHub)"
              firebase database:remove /cards/$key \
                --project nft-cards-1cd82 \
                --token "$FIREBASE_TOKEN"
            fi
          done
