name: Sync Cards to Firebase

on:
  push:
    paths:
      - 'cards/*.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Sync to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          for file in cards/*.json; do
            CARD_ID=$(basename "$file" .json)
            firebase database:set /cards/$CARD_ID "$file" --project YOUR_PROJECT_ID --token "$FIREBASE_TOKEN"
          done
